version: '3'
services:
  swgcodegen:
    image: "RPX100/swagger/codegen:${IMAGE_CODEGEN_VERSION}"
    container_name: "RPX100_swgcodegen"
    volumes:
      - "${RPX100_BASE}:/opt/build/RPX100:rw"
    networks:
      default:
        ipv4_address: 172.20.0.2
    stdin_open: true
    tty: true
  swgserver:
    image: "RPX100/swagger/server:${IMAGE_SERVER_VERSION}"
    container_name: "RPX100_swgserver"
    volumes:
      - "${RPX100_BASE}:/opt/build/RPX100:rw"
    expose:
      - "8081"
    networks:
      default:
        ipv4_address: 172.20.0.3
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  172.20.0.0/16
